web:
  image: nginx
  volumes:
    - ./docker/default.conf:/etc/nginx/conf.d/default.conf
    - ./app:/var/www/html
  links:
    - php:php-fpm
  environment:
    VIRTUAL_HOST: example.dev,www.example.dev

mysql:
  image: mysql:5.6
  volumes:
    - ./docker/database:/var/lib/mysql
    - ./docker/my.conf:/etc/mysql/my.cnf
  environment:
    MYSQL_ROOT_PASSWORD: 123
    MYSQL_DATABASE: db
    MYSQL_USER: user
    MYSQL_PASSWORD: pass

redis:
  image: redis

elastic:
  image: elasticsearch

php:
  build: .
  #image: droptica/drupal-php-fpm:xdebug
  links:
    - redis:redis
    - elastic:elastic
    - mysql:mysql
  volumes:
    - ./app:/var/www/html
    - ./docker/php.ini:/usr/local/etc/php/conf.d/php.ini